#!/bin/bash
echo "# DO NOT EDIT" > docker-compose.yml
echo "# This is generated by docker-compose-generate.sh from docker-compose-dev.yml" >> docker-compose.yml
cat docker-compose-dev.yml | grep -v "# FOR DEV ONLY" >> docker-compose.yml
